Sprint 5/step 1
temarazin/react-burger pull request #5
Opened 2023-01-26 05:03 UTC by temarazin

2023-01-26 06:40 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Реализована страница ленты заказов;
- Теперь пользователь может посмотреть историю заказов;

### **Но есть несколько замечаний, которые нужно исправить:**

- Давайте тут оставим 3 столбика по 5 элементов) как это сделано в макете: <https://disk.yandex.com/i/qkZlnIcgWp8GrA>;

- У вас не закрывается сокет соединение (Хотя редакс у вас корректно отрабатывает в этом плане), когда пользователь уходит со страницы `/feed` и `/profile/orders`. По чек-листу: Сокет-соединение открывается, когда пользователь переходит на экраны «Лента заказов» или «История заказов», и закрывается, когда пользователь покидает их. <https://disk.yandex.com/i/_C0isd6ma5AqBw> - это можно проверить в девтулс, во вкладке `networks`.

- Не отображается информация о заказе, если открыть маршрут `profile/orders/:id` в новой вкладке, хотя похожий функционал `/feed/:id` у вас работает корректно.

- У вас идёт бесконечный loading, если не авторизированный пользователь попытается зайти по ссылкам: `/login`, `profile/orders/:id` и т.д., где используется `protect-route`. По идее его должно перекинуть на авторизацию), а у вас происходит бесконечный loading;

- При запуск приложения у вас два раза вызывается запрос `GET /ingredients`, а должен вызываться 1 раз (Оставьте вызов, который в компоненте app, а в компоненте `burger-ingredients` уберите).

### **Сделает код лучше:**

- Нам не нужно указывать тип у стейта в хуке useSelector) `useSelector((store: RootState) => ...)`, вы ведь уже используете типизированный хук.

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

### **После исправления всех замечаний, работа будет принята)**

2023-01-26 06:40 UTC, ArslanDev666 commented on src/components/burger-ingredient/burger-ingredient.tsx
> +  const { ingredients } = useSelector((store: RootState) => store.burgerConstructor);
**Можно лучше:**

Тут нам не нужно указывать тип явно) `store: RootState`, вы ведь уже используете типизированный хук.

2023-01-26 06:40 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.tsx
> +  const { isAuth } = useSelector((store: RootState) => store.user);
**Можно лучше:**

здесь и в других местах.

Тут нам не нужно указывать тип явно) `store: RootState`, вы ведь уже используете типизированный хук.

2023-01-26 06:40 UTC, ArslanDev666 commented on src/components/feed-item/feed-item.tsx
> +        let price = item?.price || 0;
**Надо исправить:**

Если переменная не переопределяется, то стоит использовать `const`, а не `let`

2023-01-26 06:40 UTC, ArslanDev666 commented on src/components/feed-screen/feed-screen.tsx
> +  const ROW_COUNT = 10;
**Можно лучше:**

Лучше вынести за пределы компонента)

2023-01-26 06:40 UTC, ArslanDev666 commented on src/components/feed-screen/feed-screen.tsx
> +    let inprogress:Array<Array<number>> = [[]];
**Надо исправить:**

Если переменная не переопределяется, то стоит использовать `const`, а не `let` массивы имеют ссылочный тип, поэтому тут тоже `const.

**Можно лучше:**

Если в массиве простые (литеральные) типы (строки, числа, и т.п.) то указывать тип явно не нужно.

2023-01-26 08:13 UTC, temarazin commented
Спасибо за ревью!

2023-01-27 02:27 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания с прошлого ревью были исправлены;

2023-01-27 05:18 UTC, merged